name: guia_motel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  flutter_svg: ^2.0.14
  intl: ^0.19.0
  shimmer: ^3.0.0
  expandable_page_view: ^1.0.17
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: MontserratAlternates
      fonts: 
        - asset: assets/fonts/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 400
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
